### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jdspaeth** [celador/ForceCode#260] opened 2019-03-15 03:28 UTC
- Issue Type: `Performance`
- Extension Name: `forcecode`
- Extension Version: `3.15.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\justin\JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt
[JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt](https://github.com/celador/ForceCode/files/2969319/JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt)
` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by daishi4u** [comment] 2019-03-15 12:12
Duplicate of #248 but if you can give me more info that would be great

**Closed by daishi4u** 2019-03-15 12:12 UTC
