### ISSUE TITLE
3.16.0 not able to save LWC

### ISSUE THREAD

**Issue by Radon7** [celador/ForceCode#277] opened 2019-04-29 08:44 UTC
After updating to 3.16.0 LWCs aren't saved to the org when changes are made.

To reproduce:
1. Create a new LWC and save it the first time. ForceCode saves it successfully.
![image](https://user-images.githubusercontent.com/11978693/56884920-721c1a00-6a6b-11e9-97dc-6c62e0130c7c.png)

2. Update something in the component and save it.
![image](https://user-images.githubusercontent.com/11978693/56885002-ab548a00-6a6b-11e9-8678-3e58c995d67f.png)

3. Retrieve from the org the component. On the org there is no changes.
![image](https://user-images.githubusercontent.com/11978693/56885030-bad3d300-6a6b-11e9-8d2c-91eb51c8710a.png)

**Comment by daishi4u** [comment] 2019-05-07 00:42
I have been unable to reproduce this so far.

**Comment by sfdcale** [comment] 2019-05-07 03:21
I was able to reproduce this.

Here is Gif showing the steps:

1. ForceCode extension installed is 3.16.0
2. Created a LWC named 'hellolwc' with simple message "Hello" and save is successful with success indicator.
3. Updated the same LWC and changed the content from "Hello" to "Hello World!" and saved the file. ForceCode shows success message with success icon.
4. Right clicked on the file and selected the option "Refresh from Server" and the retrieved content doesn't have changes made in Step 3.


![Peek 2019-05-06 20-15](https://user-images.githubusercontent.com/11079913/57269359-03772780-703c-11e9-985b-caa964b11cf6.gif)

**Comment by Radon7** [comment] 2019-05-07 07:16
@daishi4u @sfdcale Exactly that. I don't know if it is useful but I'm working on MacOS.

**Comment by daishi4u** [comment] 2019-05-09 00:09
Is everyone creating the lwc via the Forcecode menu? If not, the metadata will be missing and most likely the component didn't deploy in the first place even though salesforce will indicated a successful deployment

**Comment by daishi4u** [comment] 2019-05-09 00:17
Next question. I see that @Radon7 is on mac. @praneethjonna @sfdcale are you both on mac as well?

**Comment by sfdcale** [comment] 2019-05-09 02:30
> Next question. I see that @Radon7 is on mac. @praneethjonna @sfdcale are you both on mac as well?

I am on Ubuntu 18.04.2 LTS (64 bit)

**Comment by praneethjonna** [comment] 2019-05-12 13:53
I am on Windows 7

**Comment by stehc93** [comment] 2019-05-18 16:18
same problem, im on mac as well. 
Steps: 
1. generate lwc with ForceCode menu.
2. deploy it
3. edit it + ForceCode save (cmd+s)
Result: no changes are made even tho ForceCode shows success icon.

**Comment by Radon7** [comment] 2019-05-31 07:08
@daishi4u no updates on this issue?

**Comment by daishi4u** [comment] 2019-06-06 01:43
Has anyone tried using the beta release to see if it solves this issue?

**Comment by blee-sf** [comment] 2019-06-12 21:19
I just tried using the beta, 3.17.0-2, and was able to save lwc updates to sf.

**Comment by daishi4u** [comment] 2019-06-26 19:03
Fixed in 3.17.0

**Closed** 2019-06-26 19:03 UTC
Labels: fixed in beta
