### ISSUE TITLE
Default user management

### ISSUE THREAD

**Issue by ReaperBeats** [celador/ForceCode#253] opened 2019-02-28 11:09 UTC
In order to have an efficient compatibility with SFDX CLI and other related plugins or apps, some mechanism that sets the default user automatically would be great. 

In my opinion, setting the selected user in ForceCode as the default user for SFDX, anytime it changes would be really useful.

**Comment by daishi4u** [comment] 2019-03-01 02:56
Here's the only issue I see with this: The CLI only allows for setting the default user when you login. This would mean that in order to set the default username each time you want to switch an org then you would need to login via the browser again...each and every time...Although there is another way that I am going to try out. I will let you know if it works or not, but no promises since this stuff is coming from the CLI :)

**Comment by daishi4u** [comment] 2019-03-01 03:18
Ok, so I got it to work. However, when changing the defaultusername the way that I am it isn't updated on Salesforce's status bar item (Their clickable select default username functionality...kinda like the forcecode menu), but IT WORKS!

**Comment by daishi4u** [comment] 2019-03-01 04:07
This is now in the beta-testing channel of the Forcecode slack group if you are interested in testing it out...version 3.15.0-3

**Comment by ReaperBeats** [comment] 2019-03-01 07:38
Thank you! I will try to test it soon.

**Comment by ReaperBeats** [comment] 2019-03-01 16:28
It seems to be working fine, but for one thing. If I set manually a default environment while being connected to another in ForceCode, this selection is memorized.

Ill show you an example: 

Imagine I have 3 sandboxes: Dev, UAT and PreProd.
If I log into Dev with ForceCode, Dev is set as the defaultusername.
Ídem with UAT.
ídem with PreProd.

Now, logged to PreProd in ForceCode, I set manually the default user (with the bottom button in VSCode) to Dev.
If I log into UAT with ForceCode, UAT is set as the defaultusername.
But it I log into PreProd again **this time Dev is set as the defaultusername.**

I've seen this happens because the file .forceCode/USERNAME/.sfdx/sfdx-config.json has the defaultusername set.

Is this an expected behaviour? Shouldn't it set the logged username everytime?

**Comment by daishi4u** [comment] 2019-03-01 18:28
Interesting. I did a little testing, and even manually running the force:config:set command to update the default username doesn't seem to reflect back to the vscode cli. I seem to have found where the issue is though and will try and update Forcecode sometime this weekend to reflect and let you know

**Comment by daishi4u** [comment] 2019-03-02 07:25
This has now been fixed in version 3.15.0-4 if you wanted to test that out 😀

**Comment by ReaperBeats** [comment] 2019-03-02 16:41
It works fine now!! Thank you so much!
I will still work with this beta version so I can notice if there is something wrong, but by now I have tested and it seems to be working fine.

BTW, I tested it on Ubuntu 18.04.2 LTS. VSCode 1.31.1 and sfdx-cli 6.55.1

**Comment by daishi4u** [comment] 2019-03-02 19:49
Nice, thanks for letting me know. I actually develop Forcecode with the same setup... Same version of Ubuntu and vscode!

**Comment by daishi4u** [comment] 2019-03-07 12:28
This is now in version 3.15.0

**Closed** 2019-03-07 12:28 UTC
Labels: enhancement, fixed in beta
