### ISSUE TITLE
Use behind an https proxy

### ISSUE THREAD

**Issue by viperx77** [celador/ForceCode#59] opened 2017-01-03 19:27 UTC
Does ForceCode work behind a https proxy?  I've configured VSCode's proxy configuration using ENV var "https_proxy" but it does not appear to work.

I get ForceCode: tunneling socket could not established, cause=read ECONNRESET

**Comment by celador** [comment] 2017-01-04 16:03
I believe this is out of scope for this project.  ForceCode uses standard http for all it's calls and only connects to your Salesforce org, so there shouldn't be any special configuration required. 

If you can hit your Salesforce Org using a curl command, you should be able to use this extension.

**Comment by viperx77** [comment] 2017-01-04 22:58
I'm behind a corporate http proxy.  Doesn't your project use JSForce?  As I understand it (and I could be wrong) JSForce will not work behind a firewall without using  [https://github.com/jsforce/jsforce-ajax-proxy](https://github.com/jsforce/jsforce-ajax-proxy) I understand if you can't support it but I just want to be clear on the issue.

**Comment by celador** [comment] 2017-01-05 03:38
I have added some changes per your request... https://github.com/celador/ForceCode/pull/60
Please review the PR

You will need to start up the proxy server yourself, this PR is just adding it to the config

**Comment by celador** [comment] 2017-01-10 22:15
The ability to add a proxyUrl to the config has been deployed.  Please let me know if it works for you.  I am closing this issue for now.

**Closed by celador** 2017-01-10 22:15 UTC

**Comment by amitkumarj1979** [comment] 2017-03-07 22:54
I tried using the new proxy setting "proxyUrl" and put in the URL of the corporate proxy server. But the issue is i get an error back saying Cannot connect to the website requested. When i checked the request it looks like the plugin is trying to hit the URL as a web request which gives the error.

**Comment by amitkumarj1979** [comment] 2017-03-07 23:49
I was able to get the proxy working by setting up the HTTP_PROXY environment variable. After that the problem i am facing is connect ETIMEDOUT. I got a similar issue with Visual Studio code plugin installation which was fixed if we set the  "http.proxyStrictSSL": false. Not sure how we can achieve this in Force Code.

**Comment by arturjsfCGI** [comment] 2018-01-25 17:54
Did you make it with the "proxyUrl" config?

**Comment by arturjsfCGI** [comment] 2018-01-25 17:55
Im having the connect ETIMEDOUT :S

![sf](https://user-images.githubusercontent.com/35462687/35403810-d2c84f90-01f8-11e8-8a36-4a45130c7398.jpg)

**Comment by datajock8** [comment] 2019-06-27 20:44
Yesterday I had no issues with FORCECODE authorizing to my org from two computers.

Today, both computers are kicking me out from ForceCode menu with "ERROR running force:auth:web:login:  connect ETIMEDOUT 13.108.233.3:443".

I tried to login through ForceCode using browser too, but get redirected to http://localhost:1717/OauthRedirect?code=aPrxJZTK7Rs03PV4hddBQKTwNio_tjE1VEeiWciltynzNWy_zRSOy2AGl57lhfObnRezqSwtQw%3D%3D&state=edb5687ebd05
