### ISSUE TITLE
Forcecode won't deploy file on save after a while

### ISSUE THREAD

**Issue by Mos-6** [celador/ForceCode#364] opened 2020-02-27 08:37 UTC
**Describe the bug**
It's hard to say when but it happens a lot when Forcecode stops deploying files into SF, which requires exiting VSC and re-enter for Forcecode to start deploying again upon cmd+s
This issue started a few months ago.

**To Reproduce**
I guess usually when working on the same file for a few minutes,  suddenly something breaks.

**Expected behavior**
When I click **CMD**+**S** (or ctrl+s for windows) the record is saved locally and Forcecode is queueing the file for uploading to Salesforce.

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode version  1.42.1
 - ForceCode Version 3.22.3

**Additional context**
This issue happens to our entire team. the workaround we are using is to use "SFDX deploy" instead.

**Comment by Net4nel** [comment] 2020-02-27 09:15
Hi, @Mos-6 , Funny that your describe that issue, i'm having the same bug over and over again.. as a salesforce developer i'm finding myself restarting VS code 5-10 times each day due to saving issues (auto save and 'Compile and save' from Force-code menu).

It'll be great i know this bug going to get fixed.

Much appreciated. 

Netanel.

**Comment by ctinghino** [comment] 2020-03-04 15:38
Same happening here, my team has lots of silent deploys errors, very dangerous. Code is locally saved and versioned, but when they test the edit it is not on the server - even if ForceCode said yes.
Since no notifications are issued, this bug really leads to inconsistencies.

**Comment by daishi4u** [comment] 2020-03-11 00:57
I am going to release a new version, the only thing that has changes is updating the dependencies, but I am unable to reproduce this with this new release. Please let me know if you are still facing the issue when you are updated to version 3.22.4

**Comment by ctinghino** [comment] 2020-03-11 08:19
Just updated to 3.22.4, unfortunately the issue is not fixed. 
Please let us know what kind of information do you need and how we can retrieve them (eg. logging?)

**Comment by daishi4u** [comment] 2020-03-13 01:43
This should be fixed in 3.22.5. Can one of you confirm, once you've been updated to the newer version?

**Comment by ctinghino** [comment] 2020-03-13 08:18
Thank you for your support @daishi4u . 
That sequence of steps does not generate errors with version 3.22.5. Asked the dev team to alert me in case they face similar errors after the extension update.
You can close the case in the meanwhile.

**Comment by daishi4u** [comment] 2020-03-13 11:33
Thanks @ctinghino I'll go ahead and close out the issue and will be keeping my eye out for comments here later down the road. Feel free to comment on this issue later if the issue resurfaces and I'll reopen it.

**Closed** 2020-03-13 11:33 UTC

**Comment by caiogrc** [comment] 2020-06-09 14:38
I am having this issue frequently but not sure how to reproduce.
I work in a huge LWC with thousands of lines and I mainly work just on this file for days. Every day I need to restart my VS at least 5 times to fix that.
But even that I got issues, because at the first restart, when I try to save it keeps saving but never completes/fails. So I need to restart again and then save it. Now it will give me a merge error and I can get back to work.

**Comment by Mos-6** [comment] 2020-06-10 11:30
This issue still persist and wasn't fixed. please reopen.
