### ISSUE TITLE
No metadata file downloaded using 'Get All Files from org'

### ISSUE THREAD

**Issue by RemiLeGuin** [celador/ForceCode#210] opened 2018-11-23 09:49 UTC
Hello,

Great work with ForceCode! However, I noticed a bug.

When retrieving metadata, the 'Get All Files from org' does not download any metadata. The task executes but quickly ends with a thumb up and a message 'Retrieve unpackaged'. However, it did not download any file.
I checked I am connected to an org, I can open the org in the browser with the ForceCode option.
All other retrieves work: 'Retrieve by package.xml', 'Get All Apex Classes', 'Get All Standard Objects', etc

1. Connect to a Salesforce org
2. Go to 'Command Palet'
3. Click on 'ForceCode Menu'
4. Select 'Retrieve Package/Metadata'
5. Select 'Get All Files from org'

Configuration:
 - OS: Windows 10
 - VSCode version: 1.29.1
 - ForceCode Version: 3.11.0
- Here is my settings file for config: [settings.txt](https://github.com/celador/ForceCode/files/2610261/settings.txt)

Could you please have a look?

Kind regards,

Remi

**Comment by daishi4u** [comment] 2018-11-24 00:38
Could you try and download all of your static resources by themselves and let me know if that works? If not, please go to the help menu in vscode and click the toggle developer tools option, then go to console and let me know if you see any errors there that may be related

**Comment by RemiLeGuin** [comment] 2018-11-24 13:30
Thanks for your help @daishi4u,

I downloaded static resources, reports, dashboards, documents and email templates and it worked.
For each of these metadata, I right-clicked on the corresponding folder in src and selected ForceCode: Refresh from server.
Then I checked in the console and saw 'Done retrieving files' each time: 
<img width="960" alt="doneretrievingfiles" src="https://user-images.githubusercontent.com/28781659/48968785-e6eab400-eff4-11e8-99c9-1aa9fc4e72de.png">

However, I noticed before retrieving, when ForceCode extension initializes, an error in the console: 
<img width="960" alt="cannotfindfr" src="https://user-images.githubusercontent.com/28781659/48968813-45179700-eff5-11e8-8ca4-b02dd77f5400.png">

Could it be related?

**Comment by daishi4u** [comment] 2018-11-24 16:38
Those errors are from the salesforce extensions, not Forcecode. What I was hoping to accomplish was narrow down which metadata type was failing to retrieve. If you say they all worked by refreshing then I'll have to dig deeper and see if anything else is going on. Thanks

**Comment by RemiLeGuin** [comment] 2018-11-25 11:54
Thank you for your assistance @daishi4u.
I will keep you informed if I notice any metadata type failing to be retrieved as I will continue to work downloading folders separately.
Best regards

**Comment by daishi4u** [comment] 2018-11-25 16:59
@RemiLeGuin I found the cause of this issue and it will be fixed in the next release

**Comment by RemiLeGuin** [comment] 2018-11-26 15:50
Awesome @daishi4u !
Five stars for you
Sorry I ruined your Sunday!

**Closed** 2018-11-29 16:16 UTC
