### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 6506868730** [celador/ForceCode#282] opened 2019-05-08 17:57 UTC
- Issue Type: `Performance`
- Extension Name: `forcecode`
- Extension Version: `3.16.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sbogolu\JohnAaronNelson.forcecode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by daishi4u** [comment] 2019-05-09 00:25
Duplicate of #268

**Closed by daishi4u** 2019-05-09 00:25 UTC
